ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
package com.oracle.sca.soapservice.scmsoaservices.getvalidpoetdata;
SPRINT 16
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.xmlns.pcbpel.adapter.db.sp.callspgetvalidpoet.InputParameters;
import com.oracle.xmlns.pcbpel.adapter.db.sp.callspgetvalidpoet.ObjectFactory;
import com.oracle.xmlns.pcbpel.adapter.db.sp.callspgetvalidpoet.OutputParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://oracle.com/sca/soapservice/SCMSOAServices/GetValidPOETData")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param inputParams
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.callspgetvalidpoet.OutputParameters
     */
    @WebMethod(action = "execute")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/CallSPGETValidPOET", partName = "POETData")
    public OutputParameters execute(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/CallSPGETValidPOET", partName = "InputParams")
        InputParameters inputParams);

}
